#!/bin/bash

echo "🔧 Gmail SMTP Configuration Helper"
echo "=================================="
echo ""
echo "Current SMTP configuration:"
grep -A 10 "# Email Configuration" .env.local
echo ""
echo "❌ The current Gmail credentials are not working."
echo "📧 Error: Username and Password not accepted (EAUTH 535)"
echo ""
echo "🔑 To fix this, you need to:"
echo "1. Enable 2-Factor Authentication on your Gmail account"
echo "2. Generate an App Password for 'Mail'"
echo "3. Update the SMTP_PASS with the generated app password"
echo ""
echo "🔗 Instructions:"
echo "1. Go to: https://myaccount.google.com/security"
echo "2. Enable '2-Step Verification' if not enabled"
echo "3. Go to '2-Step Verification' > 'App passwords'"
echo "4. Generate app password for 'Mail'"
echo "5. Replace SMTP_PASS in .env.local with the generated password"
echo ""
echo "📝 Example .env.local format:"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587" 
echo "SMTP_USER=your-email@gmail.com"
echo "SMTP_PASS=your-16-char-app-password"
echo ""
echo "⚠️  Note: Do NOT use your regular Gmail password!"
echo "   You MUST use the generated App Password."

