/** Contextual placeholders for admin forms — no auto-generated label text. */
export const PH = {
  title: "e.g. Welcome to Our Company",
  subtitle: "e.g. How we work with you",
  badge: "e.g. About Us",
  description: "Brief description for this section…",
  heroDescription: "Main message shown on the homepage hero…",
  buttonText: "e.g. Learn More",
  link: "e.g. /about",
  videoUrl: "https://… or YouTube/Vimeo URL",
  number: "0",
  statLabel: "e.g. Years Experience",
  featureTitle: "Feature name",
  featureDescription: "Short feature description…",
  stepNumber: "e.g. 1",
  stepTitle: "Step title",
  stepDescription: "What happens in this step…",
  email: "name@company.com",
  phone: "+1 (555) 000-0000",
  address: "Street, city, country…",
  copyright: "© 2026 Company Name",
  linkName: "Menu label",
  linkUrl: "e.g. /products",
  socialUrl: "https://…",
  newsletterHeading: "e.g. Stay Updated",
  emailPlaceholder: "e.g. Enter your email",
  formHeading: "e.g. Get in touch",
  successMessage: "Message shown after submit…",
  privacyText: "Privacy notice below the form…",
  companyDescription: "Short company blurb for the footer…",
  modalTitle: "e.g. Enquiry Now",
  ctaButton: "e.g. Enquiry Now",
  officeTitle: "e.g. Office",
  contactTitle: "e.g. Email",
} as const;
