import type { Product, Category, Service } from "@/types"

export const seedCategories: Category[] = [
  {
    id: "cat_1",
    name: "Cardiovascular",
    slug: "cardiovascular",
    description: "APIs for cardiovascular and heart-related medications",
  },
  {
    id: "cat_2",
    name: "Antibiotics",
    slug: "antibiotics",
    description: "Antibiotic active pharmaceutical ingredients",
  },
  {
    id: "cat_3",
    name: "Analgesics",
    slug: "analgesics",
    description: "Pain relief and anti-inflammatory compounds",
  },
  {
    id: "cat_4",
    name: "Antidiabetic",
    slug: "antidiabetic",
    description: "Diabetes management pharmaceutical ingredients",
  },
]

export const seedProducts: Product[] = [
  {
    id: "prod_1",
    name: "2-(4-Isobutylphenyl)propionic acid",
    slug: "2-4-isobutylphenyl-propionic-acid",
    description: "High-purity ibuprofen API for anti-inflammatory and analgesic applications",
    casNumber: "15687-27-1",
    hsCode: "2916.32.00",
    category: "Analgesics",
    molecularFormula: "C13H18O2",
    molecularWeight: "206.28",
    inStock: true,
    specifications: {
      purity: "≥99.0%",
      appearance: "White crystalline powder",
      solubility: "Soluble in ethanol, acetone",
      storage: "Store in cool, dry place",
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "prod_2",
    name: "N-(4-Hydroxyphenyl)acetamide",
    slug: "n-4-hydroxyphenyl-acetamide",
    description: "Pharmaceutical grade paracetamol for analgesic and antipyretic formulations",
    casNumber: "103-90-2",
    hsCode: "2924.29.00",
    category: "Analgesics",
    molecularFormula: "C8H9NO2",
    molecularWeight: "151.16",
    inStock: true,
    specifications: {
      purity: "≥99.5%",
      appearance: "White crystalline powder",
      solubility: "Slightly soluble in water",
      storage: "Store at room temperature",
    },
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "prod_3",
    name: "1,1-Dimethylbiguanide hydrochloride",
    slug: "1-1-dimethylbiguanide-hydrochloride",
    description: "High-quality metformin HCl for antidiabetic pharmaceutical applications",
    casNumber: "1115-70-4",
    hsCode: "2925.29.00",
    category: "Antidiabetic",
    molecularFormula: "C4H12ClN5",
    molecularWeight: "165.62",
    inStock: true,
    specifications: {
      purity: "≥99.0%",
      appearance: "White crystalline powder",
      solubility: "Freely soluble in water",
      storage: "Store in cool, dry place",
    },
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
  {
    id: "prod_4",
    name: "(S)-2-(6-Methoxynaphthalen-2-yl)propanoic acid",
    slug: "s-2-6-methoxynaphthalen-2-yl-propanoic-acid",
    description: "Premium naproxen API for NSAID formulations",
    casNumber: "22204-53-1",
    hsCode: "2918.99.00",
    category: "Analgesics",
    molecularFormula: "C14H14O3",
    molecularWeight: "230.26",
    inStock: true,
    specifications: {
      purity: "≥99.0%",
      appearance: "White to off-white powder",
      solubility: "Practically insoluble in water",
      storage: "Store protected from light",
    },
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "prod_5",
    name: "3-(10,11-Dihydro-5H-dibenzo[b,f]azepin-5-yl)propan-1-amine",
    slug: "3-10-11-dihydro-5h-dibenzo-b-f-azepin-5-yl-propan-1-amine",
    description: "Pharmaceutical grade imipramine for antidepressant applications",
    casNumber: "50-49-7",
    hsCode: "2933.99.00",
    category: "Cardiovascular",
    molecularFormula: "C19H24N2",
    molecularWeight: "280.41",
    inStock: false,
    specifications: {
      purity: "≥99.0%",
      appearance: "White to yellowish powder",
      solubility: "Soluble in ethanol",
      storage: "Store in cool, dry place",
    },
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "prod_6",
    name: "(6R,7R)-7-[[(2Z)-2-(2-Aminothiazol-4-yl)-2-methoxyiminoacetyl]amino]-3-[(1-methyltetrazol-5-yl)sulfanylmethyl]-8-oxo-5-thia-1-azabicyclo[4.2.0]oct-2-ene-2-carboxylic acid",
    slug: "ceftriaxone-sodium",
    description: "High-purity ceftriaxone sodium for antibiotic formulations",
    casNumber: "104376-79-6",
    hsCode: "2941.90.00",
    category: "Antibiotics",
    molecularFormula: "C18H16N8Na2O7S3",
    molecularWeight: "598.54",
    inStock: true,
    specifications: {
      purity: "≥98.5%",
      appearance: "White to yellowish powder",
      solubility: "Freely soluble in water",
      storage: "Store at 2-8°C",
    },
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "prod_7",
    name: "(2S,5R,6R)-6-[[(2R)-2-Amino-2-phenylacetyl]amino]-3,3-dimethyl-7-oxo-4-thia-1-azabicyclo[3.2.0]heptane-2-carboxylic acid",
    slug: "amoxicillin-trihydrate",
    description: "Pharmaceutical grade amoxicillin for broad-spectrum antibiotic use",
    casNumber: "61336-70-7",
    hsCode: "2941.10.00",
    category: "Antibiotics",
    molecularFormula: "C16H19N3O5S·3H2O",
    molecularWeight: "419.45",
    inStock: true,
    specifications: {
      purity: "≥98.0%",
      appearance: "White crystalline powder",
      solubility: "Slightly soluble in water",
      storage: "Store below 25°C",
    },
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
  },
  {
    id: "prod_8",
    name: "2-Acetoxybenzoic acid",
    slug: "2-acetoxybenzoic-acid",
    description: "High-quality aspirin API for analgesic and antiplatelet applications",
    casNumber: "50-78-2",
    hsCode: "2918.22.00",
    category: "Analgesics",
    molecularFormula: "C9H8O4",
    molecularWeight: "180.16",
    inStock: true,
    specifications: {
      purity: "≥99.5%",
      appearance: "White crystalline powder",
      solubility: "Slightly soluble in water",
      storage: "Store in cool, dry place",
    },
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "prod_9",
    name: "3-[2-[4-(6-Fluoro-1,2-benzoxazol-3-yl)piperidin-1-yl]ethyl]-2-methyl-6,7,8,9-tetrahydropyrido[1,2-a]pyrimidin-4-one",
    slug: "risperidone",
    description: "Premium risperidone API for antipsychotic pharmaceutical formulations",
    casNumber: "106266-06-2",
    hsCode: "2933.99.00",
    category: "Cardiovascular",
    molecularFormula: "C23H27FN4O2",
    molecularWeight: "410.49",
    inStock: true,
    specifications: {
      purity: "≥99.0%",
      appearance: "White to slightly beige powder",
      solubility: "Practically insoluble in water",
      storage: "Store protected from light",
    },
    createdAt: new Date("2024-01-23"),
    updatedAt: new Date("2024-01-23"),
  },
  {
    id: "prod_10",
    name: "8-Chloro-1-methyl-6-phenyl-4H-[1,2,4]triazolo[4,3-a][1,4]benzodiazepine",
    slug: "alprazolam",
    description: "Pharmaceutical grade alprazolam for anxiolytic applications",
    casNumber: "28981-97-7",
    hsCode: "2933.99.00",
    category: "Cardiovascular",
    molecularFormula: "C17H13ClN4",
    molecularWeight: "308.76",
    inStock: false,
    specifications: {
      purity: "≥99.0%",
      appearance: "White to off-white powder",
      solubility: "Insoluble in water",
      storage: "Store in cool, dry place",
    },
    createdAt: new Date("2024-01-24"),
    updatedAt: new Date("2024-01-24"),
  },
  {
    id: "prod_11",
    name: "1-Cyclopropyl-6-fluoro-4-oxo-7-piperazin-1-ylquinoline-3-carboxylic acid",
    slug: "ciprofloxacin",
    description: "High-purity ciprofloxacin for fluoroquinolone antibiotic formulations",
    casNumber: "85721-33-1",
    hsCode: "2933.49.00",
    category: "Antibiotics",
    molecularFormula: "C17H18FN3O3",
    molecularWeight: "331.34",
    inStock: true,
    specifications: {
      purity: "≥98.5%",
      appearance: "Light yellow crystalline powder",
      solubility: "Sparingly soluble in water",
      storage: "Store protected from light",
    },
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "prod_12",
    name: "3-(4,5-Dihydro-1H-imidazol-2-ylmethyl)-2,4-dimethylpyridine",
    slug: "tolazoline-hydrochloride",
    description: "Pharmaceutical grade tolazoline HCl for vasodilator applications",
    casNumber: "59-97-2",
    hsCode: "2933.39.00",
    category: "Cardiovascular",
    molecularFormula: "C10H13N3·HCl",
    molecularWeight: "196.68",
    inStock: true,
    specifications: {
      purity: "≥99.0%",
      appearance: "White crystalline powder",
      solubility: "Freely soluble in water",
      storage: "Store at room temperature",
    },
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26"),
  },
]

export const seedServices: Service[] = [
  {
    id: "svc_1",
    name: "CMO",
    slug: "cmo",
    title: "Contract Manufacturing Organization",
    description: "Comprehensive contract manufacturing services for pharmaceutical products",
    shortDescription: "End-to-end manufacturing solutions with quality assurance",
  },
  {
    id: "svc_2",
    name: "CDMO",
    slug: "cdmo",
    title: "Contract Development & Manufacturing Organization",
    description: "Integrated development and manufacturing services from concept to commercialization",
    shortDescription: "Development and manufacturing from concept to market",
  },
  {
    id: "svc_3",
    name: "Partnering",
    slug: "partnering",
    title: "Strategic Pharmaceutical Partnerships",
    description: "Collaborative partnerships for innovation, research, and market expansion",
    shortDescription: "Strategic partnerships for growth and innovation",
  },
]
